### ISSUE TITLE
default branch name

### ISSUE THREAD

**Issue by acoburn** [webidcg/webid-context#1]
This is more of a discussion than an issue (this is also dangerously close to bikeshedding, which I fully realize).

It is excellent that the context document is published online at `https://webidcg.github.io/webid-context/webid.json` via GitHub's pages mechanism. I see that the default branch is also currently set as `gh-pages`. Would it be more conventional for the default branch to be `main` and just configure the repo to serve the pages from that (`main`) branch?

**Comment by melvincarvalho** [comment]
Certainly we can do that, yes

**Comment by acoburn** [comment]
done. the default branch is now `main` and the Pages configuration has been adjusted.

**Comment by melvincarvalho** [comment]
I didn't actually know you could do that, awesome!
